### PR TITLE
Spanish (Castillian, Spain) translation and cultural interpretation. Minor adjustements in order to keep it coherent.

### PR DESCRIPTION
**Pull request by FeRChImoNdE**
I completed the "Minecraft Main Menu" part at 100%

The idea is to continue completing all the git parts translation at a calm pace.

### CODE REVIEW

**Comment by Lxtharia** [comment]
I think what still needs translation is the `E for Options / C for Console` line (which is a png).

If you tell me what the correct translation is, I can update the image :)

**Comment by FeRChImoNdE** [comment]
> I think what still needs translation is the `E for Options / C for Console` line (which is a png).
> 
> If you tell me what the correct translation is, I can update the image :)

You're totally right. Didn't notice until you pointed it 😅
Options=Opciones
Console=Consola
The actual keys are hardcoded into grub, so 'E' and 'C' remain the same. Thanks for letting me ferret your code around 😁👍🏻

**Comment by Lxtharia** [comment]
Added the bar :)

To be a 100% translation the preview in the README needs editing as well, but I think it's fine anyway.

**Comment by FeRChImoNdE** [comment]
It's perfect mate! Tomorrow i'll include it, as well as moving forward the translation a bit further. Good night!

**Comment by FeRChImoNdE** [comment]
Almost done with README.md, i'll take a screenshot for the main page if have time, but isn't critical.

Captura de pantalla_20240530_053626

I realized that I have wasted a lot of time explaining the grub and grub2 part, when I could have directly made a shell script install.sh that detects which version is installed and copies the files to the appropriate folder. It would have been faster than all the explanation I have given. xDDD

**Comment by Lxtharia** [comment]
Oh damn, yea, that's a very thorough explanation xD

I've worked on a installation Script before (in another branch) but never merged it cause i didn't test it enough.

I should maybe do that

**Comment by FeRChImoNdE** [comment]
IMG_20240530_120502
Provisional

**Comment by Lxtharia** [comment]
Looks like someone force pushed.

Please don't force push.

**Comment by FeRChImoNdE** [comment]
In my rush I made a mistake between the vscode interface, the command line and the web interface

**Comment by Lxtharia** [comment]
I can send you the git commands to fix it, or you temporarily add me as a collaborator to your fork so I can fix it x)

git can be confusing sometimes :>

**Comment by FeRChImoNdE** [comment]
Will reading github 101 meanwhile 🤣🤣🤣🤣

**Comment by Lxtharia** [comment]
Merged your 3 independent commits into the main branch that got overriden through the force push.
So it now has all changes.
I also noticed you changed some values and code, indepentendly from the translation which kinda broke some stuff (the choose background theme script failed, the theme can't font the font files). 

I also switched the preview image to a screenshot from my VM (for higher quality!)

I really don't have the energy to maintain this, but please look it retains the quality and functionality and focus only on translation. For other changes, use another branch on your fork.
thanx

**Comment by FeRChImoNdE** [comment]
You're right, i'll focus only on translate. For making experiments i could make a branch or a totally different repo 👍🏻👍🏻👍🏻

**Pull request closed without merging**
