### PR TITLE
Randomize background

### PR DESCRIPTION
**Pull request by Samsu-F**
Enhance the python script so that it also chooses a random background. This feature is easy to disable by simply deleting/renaming the unwanted background images, if one wishes to always use the same background.

### CODE REVIEW

**Comment by Lxtharia** [comment]
Thanks!
One concern I have is that the backgrounds are quite a big amount of data for boot partitions that are only 100MB in size.
I also think having a static background would be a better default option so I would suggest having an empty minegrub/backgrounds folder in the boot partition and letting the user manually copy backgrounds that should be randomly chosen from.

**Comment by Samsu-F** [comment]
that's a good point, I have changed it as suggested by you

**Comment by Lxtharia** [comment]
Looks good, I will test it in next few days hopefully, only thing I wonder is why you replaced the 1.17 amethyst geode background xd

**Comment by Samsu-F** [comment]
> only thing I wonder is why you replaced the 1.17 amethyst geode background
Because the 1.17 image used so far has some white pixels at the bottom, which bugged me a little bit

**Comment by Lxtharia** [comment]
Oh my god, I didn't notice it was the background, I thought it was some bug with text being rendered at the very bottom or something haha.
Thank you I will fix that (I like the full geode image more where you don't see the ore blocks on the left x)

**Pull request merged**
